addons:
  postgresql: '9.4'
before_script:
  - "psql -c 'create database travis_ci_test;' -U postgres"
  - "python manage.py makemigrations"
  - "python manage.py migrate"
  - "pylint Alejandria books *.py --errors-only"
cache: pip
env:
- DATABASE_URL=postgres://postgres:postgres@localhost:5432/travis_ci_test
install:
- pip install -r requirements.txt
language: python
python:
- 3.8
script:
  - pytest --cov
after_success:
  - coveralls
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: d0ab4f86-3a30-4b1f-9933-c31ab47532f2
    app: alejandria-es
  on:
    repo: UB-ES-2020-A/Alejandria
    branch: main
  skip_cleanup: true
