language: python # => 1
    python: # => 2
      - "3.8"
    services: # => 3
      - postgresql
    env: # => 4
      -DJANGO=3.1.2
    install: # => 5
      - pip install -r requirements.txt

    before_script: # => 6
      - psql -c "CREATE DATABASE Alejandro_DB;" -U Alejandro
    script: # => 7
      - pytest