services:
  - postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py makemigrations
- python manage.py migrate
- pylint Alejandria books *.py --errors-only
env:
- DATABASE_URL=postgres://postgres:postgres@localhost:5432/travis_ci_test
cache: pip
install:
- pip install -r requirements.txt
language: python
python:
- 3.8
script:
- pytest --cov
after_success:
- coveralls
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: 19KWk0dZ01B1nVm6xSRwmlUn2fIZ38tsdCaO070Ykh9p5bFEK9pdJ4W5UQMGSx0wJRU2ZpY2fTSIOvJfSDnX1QuqnNFignSo1roAT5OU6c6DNpNiWIlg0nAn3M898AVblyNA6r6d9o8WhZoTs/H3Kt47qJh3snOB92u0vXBGWzgaLx4pGhFkGIgc+5fpc1Sv2vCwZ+d9rYmEySGjspJFCNcKWEyJaDuImOLLtRfrXkoQR5BYujdfu55ptqOJPrCiGv7l7TiRT2udpYGT9tgZ/qNs0TLN2WPmgtPZ4tq3eMCKK65Z/1I75cCeBwzzYY6oBuLY/TvTLVyr7+aQvwsznfplW+ufsHMsfSfA1+dLmV7YfqRy7A9OM0fSlcnLYQXkQlRv1GX6omSYgkBtpAPnAIXr73lHxoza1hv9bhRZgRoshzMfJSMdgacHzxIMU2xo4rqMVY8fKYUmSV1SCQwJTsHYrCsLN/SvayT+hLuq2AZ6wOyYOw9lVxO2ZyJJVRKX/Nz3pWNoeWcxtmz619/IAaaAMv4UABsHfmiipl1CbxnC/Sp7DjHHBJFgHoQjrade6nVAOnlvDr7aaUhb5C8mUzjGJS2P/Eot25wNbfMRxfajtgaQDlmkYCXVEadIshnIVAFpEi3LU07Ec3tyP7msk0g9mP5oDJ9F0MTFmTp/g2M=
  skip_cleanup: true
  app:
    main: alejandria-es
    develop: alejandria-staging
