addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py makemigrations
- python manage.py migrate
cache: pip
env:
- DATABASE_URL=postgres://postgres:postgres@localhost:5432/travis_ci_test
install:
- pip install -r requirements.txt
language: python
python:
- 3.8
script:
- pytest
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: jxePUqwljtXiTfQbCC1u3extIO+QJz03VQNKxf4lgclVrL7dHcweHFBFWjZoXTwpm0HK8idFIW0+yiVqPE9/bK6AER9qVeaVHmcXqdfORFi/kUmTjhQRorw6NNoXj+YdnW6m/977EX5Nwmn/Tg+UQdHBufGhFk+PN3P6/Ynyg90GEodYLwivJatIjpf0yof1vbm/Zv18c12iSxhKP9uoq2SbY0Syet8e8peXsa08jynzlhEHL2UzDsfKYArV6shS6RWrtaEiESnaw89Wz2VChJNLYa4DbIZ+t4OohxVs+ia82NcQh1OqurrucuWxswFkcEa8tTNzmUrN+y2piiJMnoHKvZPwxujcQHGv7zNWeHvEj69E2s8tHJJCb9uBUsLU2Njb6O+jXpL5jrbSyuN30X6OefcqtGupWiSpuIAet3Yuq1ftKVua6z1R/5jfDulIPh5of0/Syv4iSmCDCsVw+Qh7zlkLhHb4yjmGMK+7+d2yfNpXI7EhHFB6rmlGcrI26odEslsCfBN86goCa1Td4iw+wnMHUeryxcanCuv8lZWGeqir3dfG+ignaIvifXkudEDBTte2wf7jMnXUEOT5RhCvJOaKzpSpCp1bpfKkb2QDvJjBU5TWb+3ulDPCF4LZc8RbJofDy/taDvvjY/hdYhThhx2+wdJd8TsOmFFgShk=
  on:
    repo: UB-ES-2020/Alejandria
    branch: main
  skip_cleanup: 'true'
