language: python # => 1
    python: # => 2
      - "3.8"
    services: # => 3
      - postgresql
    # Addons
    addons:
      postgresql: '12.4'
    env: # => 4
      -DJANGO=3.1.2
    install: # => 5
      - pip install -r requirements.txt
    before_script: # => 6
      - psql -c 'create database travisci;' -U postgres
      - python manage.py makemigrations
      - python manage.py migrate
    script: # => 7
      - pytest