addons:
  postgresql: "9.4"
before_script:
  - "psql -c 'create database travis_ci_test;' -U postgres"
  - "python manage.py makemigrations --merge"
  - "python manage.py makemigrations"
  - "python manage.py migrate"
cache: pip
env:
  - "DATABASE_URL=postgres://postgres:postgres@localhost:5432/travis_ci_test"
install:
  - "pip install -r requirements.txt"
language: python
python:
  - 3.8
script:
  - pytest
sudo: false