addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py makemigrations
- python manage.py migrate
cache: pip
env:
- DATABASE_URL=postgres://postgres:postgres@localhost:5432/travis_ci_test
install:
- pip install -r requirements.txt
language: python
python:
- 3.8
script:
- pytest
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: y7MolEA6jBR2LxH+jmsquPI1+dJXFMqRuPQP6fTdXuMkyEMGVDYnYKc/vy96VstGNcWUR8C5v1j4FLrKsJ5PS5iScGCamZ2xcpMQxHIkRWpIJglNC6ACZuhis6pqM3XWSXdkW6PMCc792VTJjO6oKzLLO76lMQV2yhwz+10QktacSSngxUejsNrYIAcUiTZM+tbRSWlE+DUywa8ycKNYaMebWNGK+HQs1mA2iO5H8WPTrjKN0JHxqiMb8QspOzogB6ya9Nr07qTEkKqWY8tmxwpm0czwNsGvqQY2nLTYMv+aXt2rBHh8SpMcZ9FKYWQGnVaHifaujgvOJLxtXGYUAQOgiYGfIruipp7GG/L+CJeaj2NTg7mHeynFICkeJMMvzJzNPnrWq4N8phtP44gMBLjh7jSNwQJSwoPXP2vOlgjuF9H2FCYzXmsogewX6oTiBgWO1QsG10dyfRMJC/1kH5S4rABLvtD8RT+MQwkWIWBYg4IxaO/MtJA1EGQMfRmIDz3ufnbYOvIOnVTW/l/NhPveTa+e6HWWiA0eucxc4jIgbQYDEaj1WeOXFT0kQdfEM2lDJXFeZVFfshJA229JlXGPPBU9YFIqunKb/0gd2IpjMwyaFYuOQrgQH1gFHtTNfnoKTOt1PMqdSv5cRZQcgMTFFKKy0fUfXdDZYwu4EI0=
    on: main
