addons: 
  postgresql: "12.4"
before_script: 
  - "psql -c 'create database travisci;' -U postgres"
  - "python manage.py makemigrations"
  - "python manage.py migrate"
env: "-DJANGO=3.1.2"
install: 
  - "pip install -r requirements.txt"
language: python
python: 
  - "3.8"
script: 
  - pytest
services: 
  - postgresql
