# Generated by Django 3.1.2 on 2020-11-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_resetmails'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetmails',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
